swagger: "2.0"
info:
  description: "KHUNECT-API"
  version: "1.0.0"
  title: "KHUNECT-API"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "sobu0715@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "13.125.196.191"
basePath: "/api"
tags:
- name: "User"
  description: "유저 관련 API"
- name: "Board"
  description: "게시판 관련 API"
- name: "Post"
  description: "게시글 API"
- name: "Test"
  description: "테스트 관련 API"
schemes:
- "https"
- "http"
paths:
  /test:
    get:
      tags:
        - Test
      summary : 서버 테스트
      description : 서버 테스트
      responses:
        '200':
          description: 서버 ON
          schema:
            type: object
            properties:
              test:
                type: boolean
                description: 서버 ON 여부
  /user/create:
    post:
      tags:
        - User
      summary : 회원 가입
      description : 회원 가입
      consumes:
        - multipart/form-data
      parameters:
        - in: formData
          name: userId
          description: 유저 아이디
          type: string
          required : true
        - in: formData
          name: password
          description: 유저 비밀번호
          type: string
          required : true
        - in: formData
          name: nickname
          description: 유저 닉네임
          type: string
          required : true
        - in: formData
          name: email
          description: 유저 이메일
          type: string
          required : true
        - in: formData
          name: major
          description: 유저 전공
          type: string
          required : true
        - in: formData
          name: image
          description: 유저 프로필 사진
          type: file
          required : true
      responses:
        '200':
          description: 회원 가입이 완료 됨
          schema:
            type: object
            properties:
              userId:
                type: string
                description: 유저 아이디
              nickname:
                type: string
                description: 유저 닉네임
        '500':
          description: 요청 실패
          schema:
            type: string
            description: 실패 이유
  /user/detail:
    get:
      tags:
        - User
      summary : 회원 정보 반환
      description : 회원 정보 반환
      parameters:
        - in: query
          name: userId
          description: 유저 아이디
          type: string
          required : true
      responses:
        '200':
          description: 회원 정보가 반환 됨
          schema:
            type: object
            properties:
              userId:
                type: string
                description: 유저 아이디
              image:
                type: string
                description: 유저 프로필 사진
              nickname:
                type: string
                description: 유저 닉네임
              major:
                type: string
                description: 전공
              email:
                type: string
                description: 유저 이메일
        '500':
          description: 요청 실패
          schema:
            type: string
            description: 실패 이유
  /user/modify:
    post:
      tags:
        - User
      summary : 회원 정보 수정
      description : 회원 정보 수정
      consumes:
        - multipart/form-data
      parameters:
        - in: formData
          name: userId
          description: 유저 아이디
          type: string
          required : true
        - in: formData
          name: password
          description: 유저 비밀번호
          type: string
          required : true
        - in: formData
          name: nickname
          description: 유저 닉네임
          type: string
          required : true
        - in: formData
          name: email
          description: 유저 이메일
          type: string
          required : true
        - in: formData
          name: image
          description: 유저 프로필 사진
          type: file
          required : true
      responses:
        '200':
          description: 회원 정보 수정 성공
          schema:
            type: string
            description: 성공 여부
        '500':
          description: 요청 실패
          schema:
            type: string
            description: 실패 이유
  /user/setLecture:
    post:
      tags:
        - User
      summary : 수강 정보 입력
      description : 수강 정보 입력
      parameters:
        - in: body
          name: body
          description: KLAS 아이디
          required : true
          schema:
            type: object
            properties:
              userId:
                type: string
                description: 유저 아이디
              klasId:
                type: string
                description: KLAS 아이디
              klasPassword:
                type: string
                description: KLAS 패스워드
      responses:
        '200':
          description: 회원 정보 수정 성공
          schema:
            type: string
            description: 성공 여부
        '500':
          description: 요청 실패
          schema:
            type: string
            description: 실패 이유
  /user/getLecture:
    post:
      tags:
        - User
      summary : 수강 정보 반환
      description : 수강 정보 입력
      parameters:
        - in: body
          name: userId
          description: KLAS 아이디
          required: true
          schema:
            type: object
            properties:
              userId:
                type: string
                description: 유저 아이디
      responses:
        '200':
          description: 회원 정보 수정 성공
          schema:
            type: array
            items:
              type: object
              properties:
                boardId:
                  type: string
                  description: boardId
                title:
                  type: string
                  description: 강좌명
                professor:
                  type: string
                  description: 교수명
        '500':
          description: 요청 실패
          schema:
            type: string
            description: 실패 이유
  /user/login:
    post:
      tags:
        - User
      summary : 로그인
      description : 로그인
      parameters:
        - in: body
          name: body
          description: 유저 로그인
          required : true
          schema:
            type: object
            properties:
              userId:
                type: string
                description: 유저 아이디
              password:
                type: string
                description: 유저 패스워드
      responses:
        '200':
          description: 로그인 성공
          schema:
            type: object
            properties:
              message:
                type: string
                description: 성공 여부
        '500':
          description: 로그인 실패
          schema:
            type: string
            description: 에러 이유
  /user/findId:
    post:
      tags:
        - User
      summary : id 찾기
      description : email을 입력해 아이디를 찾는다.
      parameters:
        - in: body
          name: body
          description: KLAS 아이디
          required : true
          schema:
            type: object
            properties:
              email:
                type: string
                description: 유저 이메일
      responses:
        '200':
          description: 회원 정보 수정 성공
          schema:
            type: array
            items:
              type: object
              properties:
                boardId:
                  type: string
                  description: boardId
                title:
                  type: string
                  description: 강좌명
                professor:
                  type: string
                  description: 교수명
        '500':
          description: 요청 실패
          schema:
            type: string
            description: 실패 이유
  /user/findPassword:
    post:
      tags:
        - User
      summary : 비밀번호 찾기
      description : 아이디와 email을 입력해 비밀번호를 초기화 한다.
      parameters:
        - in: body
          name: body
          description: 회원 정보
          required : true
          schema:
            type: object
            properties:
              userId:
                type: string
                description: 유저 아이디
              email:
                type: string
                description: 유저 이메일
      responses:
        '200':
          description: 회원 정보 수정 성공
          schema:
            type: array
            items:
              type: object
              properties:
                message:
                  type: string
                  description: 성공 여부
        '500':
          description: 요청 실패
          schema:
            type: string
            description: 실패 이유
  /post/create:
    post:
      tags:
        - Post
      summary : 게시글 생성
      description : 게시글 생성
      consumes:
        - multipart/form-data
      parameters:
        - in: formData
          name: writerId
          description: 작성자 아이디
          type: string
          required: true
        - in: formData
          name: title
          description: 게시글 제목
          type: string
          required: true
        - in: formData
          name: context
          description: 게시글 내용
          type: string
          required: true
        - in: formData
          name: boardId
          description: 게시판 ID
          type: string
          required: true
        - in: formData
          name: image
          description: 이미지
          type: file
          required: true
      responses:
        '200':
          description: 게시글 작성 성공
          schema:
            type: string
            description: 게시글 작성이 성공했다는 뜻이다.
        '500':
          description: 게시글 작성 실패
          schema:
            type: string
            description: 실패 이유
  /post/delete:
    post:
      tags:
        - Post
      summary : 게시글 삭제
      description : 게시글 삭제
      consumes:
        - multipart/form-data
      parameters:
        - in: formData
          name: writerId
          description: 작성자 아이디
          type: string
          required: true
        - in: formData
          name: postId
          description: 게시글 아이디
          type: string
          required: true
      responses:
        '200':
          description: 게시글 삭제 성공
          schema:
            type: string
            description: 게시글 삭제가 성공했다는 뜻이다.
        '500':
          description: 게시글 작성 실패
          schema:
            type: string
            description: 실패 이유
  /post/modify:
    post:
      tags:
        - Post
      summary : 게시글 수정
      description : 게시글 수정
      consumes:
        - multipart/form-data
      parameters:
        - in: formData
          name: writerId
          description: 작성자 아이디
          type: string
          required: true
        - in: formData
          name: postId
          description: 게시글 아이디
          type: string
          required: true
        - in: formData
          name: title
          description: 게시글 제목
          type: string
        - in: formData
          name: context
          description: 게시글 아이디
          type: string
      responses:
        '200':
          description: 게시글 삭제 성공
          schema:
            type: string
            description: 게시글 삭제가 성공했다는 뜻이다.
        '500':
          description: 게시글 작성 실패
          schema:
            type: string
            description: 실패 이유
  /post/recommend:
    post:
      tags:
        - Post
      summary : 게시글 추천
      description : 유저 명의로 게시글 추천
      parameters:
        - in: body
          name: body
          description: 유저, 게시글 정보
          required : true
          schema:
            type: object
            properties:
              userId:
                type: string
                description: 유저 아이디
              postId:
                type: string
                description: 게시글 Object 아이디
      responses:
        '200':
          description: 성공 여부
          schema:
            type: object
            properties:
              message:
                type: string
                description: 성공 여부
        '500':
          description: 실패 여부
          schema:
            type: object
            properties:
              message:
                type: string
                description: 실패 이유
  /post/detail/{postId}:
    get:
      tags:
        - Post
      summary : 게시글 정보 반환
      description : 게시글 정보 반환
      parameters:
        - in: path
          name: postId
          description: 게시글 아이디
          type: string
          required : true
      responses:
        '200':
          description: 게시글 정보가 반환 됨
          schema:
            type: object
            properties:
              _id:
                type: string
                description: 게시글 아이디
              writerId:
                type: string
                description: 유저 아이디
              writerNickname:
                type: string
                description: 유저 프로필 사진
              writerImage:
                type: string
                description: 유저 닉네임
              postTitle:
                type: string
                description: 게시글 제목
              postContext:
                type: string
                description: 게시글 내용
              postComments:
                type: array
                items:
                  type: object
                  properties:
                    writerNickname:
                      type: string
                      description: 닉네임 내용
                    context:
                      type: string
                      description: 댓글 내용
              postRecommend:
                type: string


        '500':
          description: 요청 실패
          schema:
            type: string
            description: 실패 이유
  /board/{boardId}/{page}:
    get:
      tags:
        - Board
      summary: boardId에 해당하는 게시판의 게시글 반환
      description: boardId에 해당하는 게시판의 게시글 반환
      parameters:
        - in: path
          name: boardId
          description: 게시판 ID
          type: string
          required: true
        - in: path
          name: page
          description: 페이지
          type: string
          required: true
        - in: query
          name: num
          description: 게시글 수
          type: string
          required: false
      responses:
        '200':
          description: 게시글 리스트 반환, post 스키마에 writerImage, writerNickname 어트리뷰트 추가
          schema:
            type: array
            items:
              type: object
              description: Post의 모델과 똑같다.
              properties:
                post:
                  type: string
                  description: Post 객체
        '500':
          description: 요청 실패
          schema:
            type: string
            description: 실패 이유
  /board/idToBoard:
    get:
      tags:
        - Board
      summary: boardId에 해당하는 게시판의 정보 반환
      description: boardId에 해당하는 게시판의 정보 반환
      parameters:
        - in: path
          name: boardId
          description: 게시판 ID
          type: string
          required: true
      responses:
        '200':
          description: 요청 성공
          schema:
            type: object
            description: Board의 모델
            properties:
              boardId:
                type: string
                description: boardId
              title:
                type: string
                description: 게시판 이름
              professor:
                type: string
                description: 교수 명
              lecture:
                type: boolean
                description: 강의 여부
        '500':
          description: 요청 실패
          schema:
            type: string
            description: 실패 이유


