swagger: "2.0"
info:
  description: "KHUNECT-API"
  version: "1.0.0"
  title: "KHUNECT-API"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "sobu0715@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "http://13.125.196.191"
basePath: "/api"
tags:
- name: "User"
  description: "유저 관련 API"
- name: "Board"
  description: "게시판 관련 API"
- name: "Post"
  description: "게시글 API"
- name: "Test"
  description: "테스트 관련 API"
schemes:
- "https"
- "http"
paths:
  /test:
    get:
      tags:
        - Test
      summary : 서버 테스트
      description : 서버 테스트
      responses:
        '200':
          description: 서버 ON
          schema:
            type: object
            properties:
              test:
                type: boolean
                description: 서버 ON 여부
  /user/create:
    post:
      tags:
        - User
      summary : 회원 가입
      description : 회원 가입
      consumes:
        - multipart/form-data
      parameters:
        - in: formData
          name: userId
          description: 유저 아이디
          type: String
          required : true
        - in: formData
          name: password
          description: 유저 비밀번호
          type: String
          required : true
        - in: formData
          name: nickname
          description: 유저 닉네임
          type: String
          required : true
        - in: formData
          name: email
          description: 유저 이메일
          type: String
          required : true
        - in: formData
          name: major
          description: 유저 전공
          type: String
          required : true
        - in: formData
          name: image
          description: 유저 프로필 사진
          type: File
          required : true          
      responses:
        '200':
          description: 회원 가입이 완료 됨
          schema:
            type: object
            properties:
              userId:
                type: string
                description: 유저 아이디
              nickname:
                type: string
                description: 유저 닉네임
        '500':
          description: 요청 실패
          schema:
            type: string
            description: 실패 이유
  /user/detail:
    get:
      tags:
        - User
      summary : 회원 정보 반환
      description : 회원 정보 반환
      parameters:
        - in: query
          name: userId
          description: 유저 아이디
          type: String
          required : true
      responses:
        '200':
          description: 회원 정보가 반환 됨
          schema:
            type: object
            properties:
              userId:
                type: string
                description: 유저 아이디
              image:
                type: string
                description: 유저 프로필 사진
              nickname:
                type: string
                description: 유저 닉네임
              major:
                type: string
                description: 전공
              email:
                type: string
                description: 유저 이메일
        '500':
          description: 요청 실패
          schema:
            type: string
            description: 실패 이유
  /user/modify:
    post:
      tags:
        - User
      summary : 회원 정보 수정
      description : 회원 정보 수정
      consumes:
        - multipart/form-data
      parameters:
        - in: formData
          name: userId
          description: 유저 아이디
          type: String
          required : true
        - in: formData
          name: password
          description: 유저 비밀번호
          type: String
          required : true
        - in: formData
          name: nickname
          description: 유저 닉네임
          type: String
          required : true
        - in: formData
          name: email
          description: 유저 이메일
          type: String
          required : true
        - in: formData
          name: image
          description: 유저 프로필 사진
          type: File
          required : true
      responses:
        '200':
          description: 회원 정보 수정 성공
          schema:
            type: string
            description: 성공 여부
        '500':
          description: 요청 실패
          schema:
            type: string
            description: 실패 이유
  /post/delete:
    post:
      tags:
        - Post
      summary : 게시글 삭제
      description : 게시글 생성
      consumes:
        - multipart/form-data
      parameters:
        - in: body
          name: writerId
          description: 작성자 아이디
          type: string
          required: true
        - in: body
          name: postId
          description: 게시글 아이디
          type: string
          required: true
      responses:
        '200':
          description: 게시글 삭제 성공
          schema:
            type: string
            description: 게시글 삭제가 성공했다는 뜻이다.
        '500':
          description: 게시글 작성 실패
          schema:
            type: string
            description: 실패 이유
  /post/create:
    post:
      tags:
        - Post
      summary : 게시글 생성
      description : 게시글 생성
      parameters:
        - in: formData
          name: writerId
          description: 작성자 아이디
          type: string
          required: true
        - in: formData
          name: title
          description: 게시글 제목
          type: string
          required: true
        - in: formData
          name: context
          description: 게시글 내용
          type: string
          required: true
        - in: formData
          name: boardId
          description: 게시판 ID
          type: string
          required: true
        - in: formData
          name: image
          description: 게시판 ID
          type: file
          required: true
      responses:
        '200':
          description: 게시글 작성 성공
          schema:
            type: string
            description: 게시글 작성이 성공했다는 뜻이다.
        '500':
          description: 게시글 작성 실패
          schema:
            type: string
            description: 실패 이유